add register view
oosuxv/WunderPferd pull request #1
Opened 2022-04-15 11:11 UTC by oosuxv

add fields logic
add custom button

2022-04-15 17:39 UTC, NosferatuHnH requested changes

2022-04-15 17:39 UTC, NosferatuHnH commented on WunderPferd/BestButton.swift
> +class BestButton: UIButton {
минор. Но на будущее в коде юмор - показатель плохого тона

2022-04-15 17:39 UTC, NosferatuHnH commented on WunderPferd/RegisterViewController.swift
> +
лишняя пустая строка

2022-04-16 07:07 UTC, oosuxv commented on WunderPferd/BestButton.swift
> +class BestButton: UIButton {
исправил naming вынес цвета в константы

2022-04-16 07:08 UTC, oosuxv commented on WunderPferd/RegisterViewController.swift
> +
исправил

2022-04-16 07:09 UTC, oosuxv commented on WunderPferd/BestButton.swift
> +class BestButton: UIButton {
а можно как-нибудь из гуевых настроек брать цвета для кнопочки?

2022-04-18 09:29 UTC, merged