Homework 03
oosuxv/WunderPferd pull request #2
Opened 2022-04-22 08:34 UTC by oosuxv

2022-04-23 06:51 UTC, NosferatuHnH requested changes

2022-04-23 06:51 UTC, NosferatuHnH commented on WunderPferd/ProfileViewController.swift
> +extension ProfileViewController: UITableViewDelegate {}
пустой экстеншен дополни пометкой // TODO: realize

2022-04-23 06:51 UTC, NosferatuHnH commented on WunderPferd/StudyScrollViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
Идея хорошая, одобряю. Но если это родитель на 2 разных экрана - лучше тут пользоваться не аутлетами, а просто пометить их как `var scrollView: UIScrollView?`. 

В наследнике 
`var scrollView {
      authScrollView //<- а вот это уже аутлет
}`
И так касательно всех аутлетов. Будет нагляднее.

2022-04-23 06:51 UTC, NosferatuHnH commented on WunderPferd/StudyScrollViewController.swift
> +class StudyScrollViewController: UIViewController {
Study убери из названия. Заодно посмотришь, как работает рефакторинг

2022-04-23 06:51 UTC, NosferatuHnH commented on WunderPferd/TableRows/ProfileTableViewCell/ProfileTableViewCell.swift
> +    }
пустые методы

2022-04-23 10:25 UTC, oosuxv commented on WunderPferd/StudyScrollViewController.swift
> +class StudyScrollViewController: UIViewController {
а как его грамотно назвать тогда? CustomScrollViewController? TitledScrollViewController?

2022-04-23 19:15 UTC, oosuxv commented on WunderPferd/ProfileViewController.swift
> +extension ProfileViewController: UITableViewDelegate {}
fixed

2022-04-24 06:34 UTC, oosuxv commented on WunderPferd/ProfileViewController.swift
> +extension ProfileViewController: UITableViewDelegate {}
fixed

2022-04-24 06:34 UTC, oosuxv commented on WunderPferd/StudyScrollViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
fixed
правда прямо через такой код не нашел как сделать, инициализацию скинул в viewDidLoad

2022-04-24 06:35 UTC, oosuxv commented on WunderPferd/StudyScrollViewController.swift
> +class StudyScrollViewController: UIViewController {
fixed

2022-04-24 06:39 UTC, oosuxv commented on WunderPferd/TableRows/ProfileTableViewCell/ProfileTableViewCell.swift
> +    }
fixed

2022-04-24 16:24 UTC, NosferatuHnH approved these changes

2022-04-24 16:30 UTC, merged