Hw05
oosuxv/WunderPferd pull request #3
Opened 2022-04-28 18:08 UTC by oosuxv

2022-04-29 17:33 UTC, NosferatuHnH requested changes

2022-04-29 17:33 UTC, NosferatuHnH commented on WunderPferd/ProfileViewController.swift
это метод датасорца

2022-04-29 17:33 UTC, NosferatuHnH commented on WunderPferd/ProfileViewController.swift
> +            cell.circledImageView.addGestureRecognizer(tapGestureRecognizer)
это делается через делегат.

2022-04-29 17:33 UTC, NosferatuHnH commented on WunderPferd/ProfileViewController.swift
> +            self.wideImageView = cell.wideImageView
вытаскивать проперти из таблицы - плохо

2022-04-29 17:33 UTC, NosferatuHnH commented on WunderPferd/ProfileViewController.swift
> +        dismiss(animated: true)
сохраняй имейджи локально, потом релоади таблицу. А при постройке забирай из этих пропертей картинки и скругляй

2022-04-30 09:43 UTC, oosuxv commented on WunderPferd/ProfileViewController.swift
fixed

2022-05-01 08:44 UTC, oosuxv commented on WunderPferd/ProfileViewController.swift
> +            self.wideImageView = cell.wideImageView
fixed

2022-05-01 08:44 UTC, oosuxv commented on WunderPferd/ProfileViewController.swift
> +        dismiss(animated: true)
fixed

2022-05-01 08:45 UTC, oosuxv commented on WunderPferd/ProfileViewController.swift
> +            cell.circledImageView.addGestureRecognizer(tapGestureRecognizer)
не понимаю какой делегат делать

2022-05-04 09:05 UTC, oosuxv commented on WunderPferd/ProfileViewController.swift
> +            cell.circledImageView.addGestureRecognizer(tapGestureRecognizer)
fixed

2022-05-08 18:34 UTC, NosferatuHnH commented on WunderPferd/ProfileViewController.swift
> +        self.tableView.reloadSections(IndexSet([0]), with: .automatic)
Аппрувлю но просто для справки. Лучше вынести в константы или делать через обновление всей таблицы. В чём суть - если ты захочешь переместить на новый индекс секцию с картинкой - тебе придётся держать в памяти, что надо перенести обновление секции после пикера. Или потом ловить баг. В маленьком проекте быстро. В большом может быть немножечко больно

2022-05-08 18:34 UTC, NosferatuHnH approved these changes

2022-05-08 19:16 UTC, merged