Hw07
oosuxv/WunderPferd pull request #4
Opened 2022-05-17 10:14 UTC by oosuxv

added authorization and registration through nanospot api

2022-05-17 12:29 UTC, NosferatuHnH requested changes

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "pins" : [
должно быть в гитигноре. Посмотри, если нет - добавь и обнови его кэш

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/BoldSnackBar.swift
> +class BoldSnackBar: SnackBar {
Либо БолдТекстСнэкБар (хотя не вижу именно выставление болд веса текста) или по смыслу - как его используешь.

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +    @IBAction func registerTap(_ sender: Any) {
showRegisterTap или registerAction с первого взгляда подумал, что ты гестур рекогнайзер добавляешь

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +    @IBAction func registerTap(_ sender: Any) {
registerButtonTap вот например так допиши

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +    @IBAction func enterTap(_ sender: Any) {
и тут батон добавь

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +            BoldSnackBar.make(in: self.view, message: "Заполните все поля.", duration: .lengthLong).show()
селф нужен?

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +            BoldSnackBar.make(in: self.view, message: "Заполните все поля.", duration: .lengthLong).show()
можно тогда и мэйк перепесать с дефолтными параметрами кстати

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +    let pnm: ProfileNetworkManager = NetworkManager()
давай без панам. profileNetworkManager / networkManager но не сокращение

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +        pnm.login(username, password) {
викифицируй

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +            }
смотри. текст ошибки ты игноришь. Тогда можно 

```
if let response = response {
                  let storageManager = StorageManager()
                  storageManager.saveToKeychain(response.token, key: .token)
                  storageManager.saveToKeychain(response.userId, key: .userId)
                  let storyboard = UIStoryboard(name: "Main", bundle: nil)
                  let tabBarVC = storyboard.instantiateViewController(identifier: "UITabBarController")
                  tabBarVC.modalPresentationStyle = .fullScreen
                  self.show(tabBarVC, sender: self)
                  return
              }
BoldSnackBar.make(in: self.view, message: "Логин провалился", duration: .lengthLong).show()
```

На сдвиг и отступы не смотри - их сделал мне гитхаб в этом дискассе. Принт тебе не нужен. Если хочешь оставить как есть - доставай в качестве текста error.localizedDescription и в верхнем ифе показывай его. А уже на самом конце функции показывай "Логин провалился" если вдруг не зашло ни туда ни туда

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/ProfileViewController.swift
> +    let pnm: ProfileNetworkManager = NetworkManager()
и опять панама

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/ProfileViewController.swift
> +            }
смотри. У тебя потенциально никнейм меняться не будет каждые 5 минут. А этот метод будет дёргаться при каждой перестройке таблицы. Сделай аналогично имэйджу.

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/RegisterViewController.swift
> +    private func validateFields() -> Bool {
hasNoValidationErrors

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/RegisterViewController.swift
> +        pnm.register(username, password) {
викифицируй

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/RegisterViewController.swift
> +            }
то же что писал про ошибку

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/RegisterViewController.swift
> +                let password = regTextFields[passwordFieldId].text,
если текста нил (невозможно тут, но потенциально). До валидейт филдс не дойдёт и юзерь не увидит алерты. Сперва валидируй, потом доставай переменные.

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/RegisterViewController.swift
> +        pnm.checkUsername(username) {
викифицируй

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Controllers/RegisterViewController.swift
> +            }
и тут про ошибки тоже самое

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Services/Response/UsernameResponse.swift
> +}
вынеси в отдельный файл

2022-05-17 12:29 UTC, NosferatuHnH commented on WunderPferd/Services/Router.swift
> +enum Router: URLRequestConvertible {
Это круто. Но роутером принято называть сущность, осуществляющую переход из контроллера. А это по сути URLRequestBuilder. Или реквест билдер. Не суть. В общем я за переименование, но круто.

2022-05-18 04:49 UTC, oosuxv commented on WunderPferd/BoldSnackBar.swift
> +class BoldSnackBar: SnackBar {
fixed

2022-05-18 05:02 UTC, oosuxv commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +    @IBAction func registerTap(_ sender: Any) {
fixed

2022-05-18 05:02 UTC, oosuxv commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +    @IBAction func enterTap(_ sender: Any) {
fixed

2022-05-18 05:06 UTC, oosuxv commented on WunderPferd/Services/Router.swift
> +enum Router: URLRequestConvertible {
мне просто не понравилось урлы собирать конкатенацией строк, поэтому в доке к аламофаеру нашел пример и доработал напильником. про naming понял
fixed

2022-05-18 06:13 UTC, oosuxv commented on WunderPferd/Controllers/ProfileViewController.swift
> +    let pnm: ProfileNetworkManager = NetworkManager()
fixed

2022-05-18 06:13 UTC, oosuxv commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +    let pnm: ProfileNetworkManager = NetworkManager()
fixed

2022-05-18 06:40 UTC, oosuxv commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +            BoldSnackBar.make(in: self.view, message: "Заполните все поля.", duration: .lengthLong).show()
fixed

2022-05-18 07:12 UTC, oosuxv commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +            }
по хорошему вместо принта надо какой-нибудь logger воткнуть, но я не дошел до разбирательств с этой частью пока
fixed

2022-05-18 07:14 UTC, oosuxv commented on WunderPferd/Controllers/RegisterViewController.swift
> +    private func validateFields() -> Bool {
fixed

2022-05-18 07:17 UTC, oosuxv commented on WunderPferd/Controllers/RegisterViewController.swift
> +                let password = regTextFields[passwordFieldId].text,
fixed

2022-05-18 10:10 UTC, oosuxv commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +        pnm.login(username, password) {
fixed

2022-05-18 10:12 UTC, oosuxv commented on WunderPferd/Controllers/RegisterViewController.swift
> +        pnm.register(username, password) {
fixed

2022-05-18 10:13 UTC, oosuxv commented on WunderPferd/Controllers/RegisterViewController.swift
> +            }
fixed

2022-05-18 10:13 UTC, oosuxv commented on WunderPferd/Controllers/RegisterViewController.swift
> +            }
fixed

2022-05-18 10:20 UTC, oosuxv commented on WunderPferd/Services/Response/UsernameResponse.swift
> +}
fixed

2022-05-18 10:20 UTC, oosuxv commented on WunderPferd/Controllers/RegisterViewController.swift
> +        pnm.checkUsername(username) {
fixed

2022-05-18 12:03 UTC, oosuxv commented on WunderPferd/Controllers/ProfileViewController.swift
> +            }
тут сделал, но мне не нравится как вышло. не знаю как лучше

2022-05-19 17:53 UTC, NosferatuHnH commented on WunderPferd/Controllers/RegisterViewController.swift
> +        hud.show(in:    self.view)
что-то с форматированием. Как минимум куча пробелов в худ шоу

2022-05-19 18:08 UTC, NosferatuHnH requested changes

2022-05-19 18:08 UTC, NosferatuHnH commented on WunderPferd/Services/ProfileDataManager.swift
> +class ProfileDataManager {
1) Весьма неплохой сервис, но опять промазал с именем. DataManager как правило работает с хранилищем данных. Сама сущность которая много чо умеет - это интерактор / провайдер / датапровайдер и так далее. Обычно он в себя получает сервисы хранилища данных и запросов в сеть. Разные сущности. В остальном он сам разруливает логику. и поступает именно так. да.

2022-05-19 18:08 UTC, NosferatuHnH commented on WunderPferd/Services/ProfileDataManager.swift
> +class ProfileDataManager {
2. Оно должно чиститься при логине / регистрации. Иначе войдёт другой юзер - увидит имя и аватар другого пользователя

2022-05-19 18:08 UTC, NosferatuHnH commented on WunderPferd/Services/ProfileDataManager.swift
> +    func requestUsername(completion: @escaping (String) -> ()) {
Наружу можешь кидать ещё и эррор тем самым сняв с сервиса ответственность за обработку. Но они тогда оба опциональные будут на манер интернет - сервиса.

2022-05-19 18:08 UTC, NosferatuHnH commented on WunderPferd/Services/StorageManager.swift
> +
пустая строка

2022-05-20 07:53 UTC, oosuxv commented on WunderPferd/Controllers/RegisterViewController.swift
> +        hud.show(in:    self.view)
fixed

2022-05-20 08:34 UTC, oosuxv commented on WunderPferd/Services/StorageManager.swift
> +
fixed

2022-05-21 11:09 UTC, oosuxv commented on WunderPferd/Services/ProfileDataManager.swift
> +class ProfileDataManager {
Починил. Переделал в Interactor, добавил туда же сохранение даных при логине\регистрации. Кажется начал понимать зачем нужен координатор, но это не точно.

2022-05-21 19:22 UTC, oosuxv commented on WunderPferd/Services/ProfileDataManager.swift
> +    func requestUsername(completion: @escaping (String) -> ()) {
не придумал как в кложуру сделать throws, сигнатуру придется менять

2022-05-22 06:19 UTC, NosferatuHnH commented on WunderPferd/Services/ProfileDataInteractor.swift
> +
пустая строка

2022-05-22 06:37 UTC, NosferatuHnH commented on WunderPferd/Services/ProfileDataManager.swift
> +    func requestUsername(completion: @escaping (String) -> ()) {
В чём трабла то?

2022-05-22 08:04 UTC, oosuxv commented on WunderPferd/Services/ProfileDataInteractor.swift
> +
fixed

2022-05-23 15:04 UTC, NosferatuHnH approved these changes

2022-05-23 15:13 UTC, merged