Hw08
oosuxv/WunderPferd pull request #5
Opened 2022-05-24 21:09 UTC by oosuxv

ServiceLocator and PlanetViewController

2022-05-25 18:08 UTC, NosferatuHnH requested changes

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/AppDelegate.swift
> +        let storageManager: StorageManager = ServiceLocator.storageManager()
закрой протоколом

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Controllers/PlanetViewController.swift
> +    private let rickNetworkManager = ServiceLocator.rickNetworkManager()
planetNetworkManager либо название плохое, либо он показывает лишние методы, которые нафиг не нужны плэнет вью контроллеру

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Controllers/PlanetViewController.swift
> +    private var maxPages = Int.max
Минор, но это можно через булфлажок разрулить и было бы нагляднее

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Controllers/PlanetViewController.swift
> +                print(error as Any)
в снекер, а не в принт

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Controllers/PlanetViewController.swift
> +                self.locationList.append(contentsOf: locations.results)
сделай верхнее ограничение по числу подгруженных планет путём очистки старых данных

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Controllers/PlanetViewController.swift
> +            }
можно с таким ограничением да, но не стоит. Более чисто будет это в вилл дисплей целл метоже

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Services/NetworkManager.swift
> +extension NetworkManager: RickNetworkManager {
таки нейминг

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Services/ServiceLocator.swift
> +    }
слово ретурн можешь везде убрать

2022-05-25 18:08 UTC, NosferatuHnH commented on WunderPferd/Services/StorageManager.swift
> +}
Один из смыслов закрытия протоколами - разграничение зоны видимости и ответственности. В таком протоколе смысла нет. А вот куча протоколов под нужные только места - уже осмысленно

2022-05-26 07:33 UTC, oosuxv commented on WunderPferd/Services/StorageManager.swift
> +}
переработал все протоколы для обеспечения разграничения

2022-05-26 07:34 UTC, oosuxv commented on WunderPferd/Services/ServiceLocator.swift
> +    }
исправил

2022-05-26 07:34 UTC, oosuxv commented on WunderPferd/Services/NetworkManager.swift
> +extension NetworkManager: RickNetworkManager {
исправил

2022-05-26 07:35 UTC, oosuxv commented on WunderPferd/Controllers/PlanetViewController.swift
> +    private let rickNetworkManager = ServiceLocator.rickNetworkManager()
исправил, переработал протоколы

2022-05-26 07:35 UTC, oosuxv commented on WunderPferd/AppDelegate.swift
> +        let storageManager: StorageManager = ServiceLocator.storageManager()
закрыл протоколом

2022-05-26 19:59 UTC, oosuxv commented on WunderPferd/Controllers/PlanetViewController.swift
> +    private var maxPages = Int.max
переписал через флаг

2022-05-26 20:00 UTC, oosuxv commented on WunderPferd/Controllers/PlanetViewController.swift
> +                print(error as Any)
fixed
принт оставил вместо логгирования. расскажешь про него в двух словах потом?

2022-05-26 20:00 UTC, oosuxv commented on WunderPferd/Controllers/PlanetViewController.swift
> +                self.locationList.append(contentsOf: locations.results)
не осилил пока

2022-05-26 20:02 UTC, oosuxv commented on WunderPferd/Controllers/PlanetViewController.swift
> +            }
перенес в  willDisplay

2022-05-26 20:26 UTC, NosferatuHnH commented on WunderPferd/Controllers/PlanetViewController.swift
> +                self.locationList.append(contentsOf: locations.results)
и нафиг его

2022-05-26 20:36 UTC, NosferatuHnH approved these changes

2022-05-26 20:37 UTC, merged