Hw13
oosuxv/WunderPferd pull request #7
Opened 2022-05-29 03:37 UTC by oosuxv

2022-05-29 17:31 UTC, NosferatuHnH requested changes

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +        authPasswordField.layer.masksToBounds = true
вынеси в отдельную функцию, вызови для каждого текстфилда её, передавая текстфилд.

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +    }
зачем?

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +        if location.residents.count == 1 {
нет разницы грузить 1 или тонну

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +                    self.collectionView.reloadData()
неа. это каждый раз дёргать обновление коллекции при параллельной загрузке?

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +        return characters.count
нет. Ты сходу показывешь все ячейки

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +    }
а если эту функцию реализовать внутри ячейки - не придётся передавать 2 параметра

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +
пустая строка

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +}
если не думаешь продолжать - можешь просто удалить

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/PlanetViewController.swift
> +        let characterListViewController = CharacterListViewController()
если в обход сториборды внезапно решил, то его на сториборде точно нет? Ну а то что неконсистентно - это минор.

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/ProfileViewController.swift
> +    var registrationDate = Date.now.addingTimeInterval(-86400)
вместо этого подтяни что-нибудь с бэка. Минор.

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Controllers/RootTabBarController.swift
> +    }
пустой метод

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Services/ImageService.swift
> +                        print(error as Any)
принт убери

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Services/StorageManager.swift
> +            print(error as Any)
принт убирай

2022-05-29 17:31 UTC, NosferatuHnH commented on WunderPferd/Services/StorageManager.swift
> +            print("first start")
и тут

2022-05-29 19:56 UTC, oosuxv commented on WunderPferd/Controllers/AuthorizeViewController.swift
> +        authPasswordField.layer.masksToBounds = true
fixed

2022-05-29 19:56 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +
fixed

2022-05-29 19:56 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +}
removed

2022-05-29 19:57 UTC, oosuxv commented on WunderPferd/Services/ImageService.swift
> +                        print(error as Any)
fixed

2022-05-29 19:57 UTC, oosuxv commented on WunderPferd/Services/StorageManager.swift
> +            print(error as Any)
fixed

2022-05-29 19:58 UTC, oosuxv commented on WunderPferd/Services/StorageManager.swift
> +            print("first start")
fixed

2022-05-30 19:57 UTC, oosuxv commented on WunderPferd/Controllers/RootTabBarController.swift
> +    }
fixed

2022-05-30 19:58 UTC, oosuxv commented on WunderPferd/Controllers/PlanetViewController.swift
> +        let characterListViewController = CharacterListViewController()
решил попробовать другой вариант. на борде точно нет. про консистенцию понял

2022-05-30 19:58 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +    }
функцию подвинул

2022-05-31 07:17 UTC, oosuxv commented on WunderPferd/Controllers/ProfileViewController.swift
> +    var registrationDate = Date.now.addingTimeInterval(-86400)
имя профиля в шапку с бека подгружается. а под цвет и дату ничего подходящего не нашел

2022-05-31 17:38 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +    }
получал всех персонажей разом. логика переписана с нуля

2022-05-31 17:38 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +        if location.residents.count == 1 {
парсер один элемент с апи не умеет переделывать в массив. логика переписана с нуля

2022-05-31 17:38 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +                    self.collectionView.reloadData()
запрос выполнялся один раз. логика переписана с нуля

2022-05-31 17:39 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +        return characters.count
логика переписана с нуля

2022-06-01 16:53 UTC, NosferatuHnH commented on WunderPferd/Controllers/CharacterListViewController.swift
> +            flowLayout.minimumInteritemSpacing = Constants.minimumInteritemSpacing
костыль

2022-06-01 18:56 UTC, oosuxv commented on WunderPferd/Controllers/CharacterListViewController.swift
> +            flowLayout.minimumInteritemSpacing = Constants.minimumInteritemSpacing
перевел на UICollectionViewCompositionalLayout

2022-06-02 05:52 UTC, NosferatuHnH approved these changes

2022-06-02 06:00 UTC, merged